project:
  type: website

website:
  title: "Janette's Marketing Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: digital-marketing.qmd
        text: Digital Marketing & Analytics
      - href: reveal-presentation.qmd
        text: Final Presentation

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css

